/**
 * @fileoverview Unit tests for js/backup-sync/services/google-sheet-service.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../../setup/module-test-utils.js';

const MODULE = '../../../../js/backup-sync/services/google-sheet-service.js';

describe('js/backup-sync/services/google-sheet-service.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["REQUIRED_SHEET_COLUMNS","fetchAllSheetRecords","getRemoteRecordCount","getSheetAction","getSpreadsheetId","healthCheck","isGoogleSheetsConfigured","postSheetPayload","validateSheetHeaders"]);
  });

});
