/**
 * @fileoverview Unit tests for js/backup-sync/services/google-sheets-destination.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../../setup/module-test-utils.js';

const MODULE = '../../../../js/backup-sync/services/google-sheets-destination.js';

describe('js/backup-sync/services/google-sheets-destination.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["getRemoteRecordCount","googleSheetsDestination","healthCheck","isGoogleSheetsConfigured","retryRecords","upsertBatch"]);
  });

});
