/**
 * @fileoverview Unit tests for js/constants/advanced-member-search.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/constants/advanced-member-search.js';

describe('js/constants/advanced-member-search.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["ADVANCED_MEMBER_SEARCH","ADVANCED_SEARCH_AGE_BUCKET_IDS","ADVANCED_SEARCH_MEMBERSHIP_FILTER_KEYS","ADVANCED_SEARCH_MEMBERSHIP_NON_MEMBER_FILTER"]);
  });

});
