/**
 * @fileoverview Unit tests for js/constants/auth.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/constants/auth.js';

describe('js/constants/auth.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["AUTH_ERRORS","ROLES","SESSION_ACTIVITY_STORAGE_KEY","SESSION_FORCE_LOGIN_KEY","SESSION_IDLE_TIMEOUT_MS","SESSION_KEY_ROLE_UI"]);
  });

});
