/**
 * @fileoverview Unit tests for js/constants/constants.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/constants/constants.js';

describe('js/constants/constants.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["ADVANCED_MEMBER_SEARCH","ADVANCED_SEARCH_AGE_BUCKET_IDS","ADVANCED_SEARCH_MEMBERSHIP_FILTER_KEYS","ADVANCED_SEARCH_MEMBERSHIP_NON_MEMBER_FILTER","AUTH_ERRORS","BIRTHDAY_DASHBOARD","BLOOD_GROUP_OPTIONS","CLOUDINARY_CONFIG","COLLECTIONS","DASHBOARD_DEFAULTS","DEFAULT_LOCALE","EDUCATION_OPTIONS","ENABLE_PHOTO_UPLOAD","FAMILY_TREE","FAMILY_TREE_LAYOUT","FAMILY_TREE_REFERRER","GENDER_OPTIONS","HOUSEHOLD_DIRECTORY","HOUSEHOLD_DIRECTORY_MEMBERSHIP_FILTER_KEYS","JILLA_MEMBERSHIP_COLUMN_LABELS","JILLA_MEMBERSHIP_MIN_YEAR","LOCALES","MEMBERSHIP_OPTIONS","MEMBER_COUNT_UNIT","MEMBER_OCCUPATION_OPTIONS","MESSAGES","OCCUPATION_OPTIONS","ORG_NAME","ORG_SUBTITLE","OUTSIDE_REASONS","PDF_ADVANCED_SEARCH","PDF_MEMBER_LIST","PRADESHIKA_SABHA_CODES","PRADESHIKA_SABHA_OPTIONS","RATION_CARD_OPTIONS","RELATIONSHIP_OPTIONS","ROLES","ROUTES","SABHA_TILE_GRADIENTS","SESSION_ACTIVITY_STORAGE_KEY","SESSION_FORCE_LOGIN_KEY","SESSION_IDLE_TIMEOUT_MS","SESSION_KEY_ROLE_UI","STORAGE_PHOTO_PATH","TIMING","VIEW_PAGE_FROM_PARAM","VIEW_REFERRER","buildFamilyTreeHref","resolveCreatePageBackNav","resolveFamilyTreeBackNav","resolveRecordsListHrefFromViewReferrer","sabhaGradientCss","sabhaGradientPair"]);
  });

});
