/**
 * @fileoverview Unit tests for js/constants/family-tree.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/constants/family-tree.js';

describe('js/constants/family-tree.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["FAMILY_TREE","FAMILY_TREE_ENABLE_FOCUS_NAVIGATION","FAMILY_TREE_LAYOUT","FAMILY_TREE_LINK_STYLES","FAMILY_TREE_NODE_ROLES","FAMILY_TREE_ROW_STEP","FAMILY_TREE_SUPPORTED_RELATIONSHIPS"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('exports frozen layout and copy constants', async () => {
      const { FAMILY_TREE_LAYOUT, FAMILY_TREE, FAMILY_TREE_SUPPORTED_RELATIONSHIPS } = await import(MODULE);
      assert.ok(FAMILY_TREE_LAYOUT.NODE_WIDTH > 0);
      assert.equal(typeof FAMILY_TREE.PAGE_TITLE, 'string');
      assert.ok(Object.isFrozen(FAMILY_TREE_SUPPORTED_RELATIONSHIPS));
    });
  });

  describe('edge cases', () => {
    it('supported relationships include in-law and grandchild keys', async () => {
      const { FAMILY_TREE_SUPPORTED_RELATIONSHIPS } = await import(MODULE);
      assert.ok(FAMILY_TREE_SUPPORTED_RELATIONSHIPS.includes('grandchild'));
      assert.ok(FAMILY_TREE_SUPPORTED_RELATIONSHIPS.includes('daughter_in_law'));
    });
  });
  });
});
