/**
 * @fileoverview Unit tests for js/constants/household-directory.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/constants/household-directory.js';

describe('js/constants/household-directory.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["HOUSEHOLD_DIRECTORY","HOUSEHOLD_DIRECTORY_MEMBERSHIP_FILTER_KEYS"]);
  });

});
