/**
 * @fileoverview Unit tests for js/constants/member-options.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/constants/member-options.js';

describe('js/constants/member-options.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["BLOOD_GROUP_OPTIONS","EDUCATION_OPTIONS","GENDER_OPTIONS","MEMBERSHIP_OPTIONS","MEMBER_OCCUPATION_OPTIONS","OCCUPATION_OPTIONS","OUTSIDE_REASONS","PRADESHIKA_SABHA_OPTIONS","RATION_CARD_OPTIONS","RELATIONSHIP_OPTIONS"]);
  });

});
