/**
 * @fileoverview Unit tests for js/constants/routing.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/constants/routing.js';

describe('js/constants/routing.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["FAMILY_TREE_REFERRER","ROUTES","VIEW_PAGE_FROM_PARAM","VIEW_REFERRER","buildFamilyTreeHref","resolveCreatePageBackNav","resolveFamilyTreeBackNav","resolveRecordsListHrefFromViewReferrer"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('resolveRecordsListHrefFromViewReferrer maps advanced search referrer', async () => {
      const { resolveRecordsListHrefFromViewReferrer, VIEW_REFERRER } = await import(MODULE);
      assert.equal(resolveRecordsListHrefFromViewReferrer(VIEW_REFERRER.ADVANCED_SEARCH), 'advanced-member-search');
      assert.equal(resolveRecordsListHrefFromViewReferrer(VIEW_REFERRER.MEMBER_LIST), 'household-directory');
    });

    it('buildFamilyTreeHref encodes id and from referrer', async () => {
      const { buildFamilyTreeHref, FAMILY_TREE_REFERRER } = await import(MODULE);
      const href = buildFamilyTreeHref('house 1', FAMILY_TREE_REFERRER.VIEW);
      assert.ok(href.includes('family-tree?id='));
      assert.ok(href.includes('from=view'));
    });
  });

  describe('negative cases', () => {
    it('resolveRecordsListHrefFromViewReferrer defaults unknown values to household directory', async () => {
      const { resolveRecordsListHrefFromViewReferrer } = await import(MODULE);
      assert.equal(resolveRecordsListHrefFromViewReferrer('unknown'), 'household-directory');
      assert.equal(resolveRecordsListHrefFromViewReferrer(null), 'household-directory');
    });
  });

  describe('edge cases', () => {
    it('resolveFamilyTreeBackNav falls back without record id', async () => {
      const { resolveFamilyTreeBackNav, FAMILY_TREE_REFERRER } = await import(MODULE);
      const nav = resolveFamilyTreeBackNav(FAMILY_TREE_REFERRER.VIEW, '');
      assert.equal(nav.href, 'household-directory');
    });
  });
  });
});
