/**
 * @fileoverview Unit tests for js/services/family-tree-inference/rules/spouse-rule.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

const INDEX_MODULE = '../../../../../js/services/family-tree-inference/index.js';

describe('js/services/family-tree-inference/rules/spouse-rule.js', () => {
  it('is registered in the inference engine', async () => {
    const { INFERENCE_RULES } = await import(INDEX_MODULE);
    assert.ok(INFERENCE_RULES.some((rule) => rule.name === 'SpouseRule'));
  });
});
