/**
 * @fileoverview Unit tests for js/services/family-tree-inference/rules/unresolved-members-rule.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../../../setup/module-test-utils.js';

const MODULE = '../../../../../js/services/family-tree-inference/rules/unresolved-members-rule.js';

describe('js/services/family-tree-inference/rules/unresolved-members-rule.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["UnresolvedMembersRule"]);
  });

});
