/**
 * @fileoverview Unit tests for js/backup-sync/backup-sync-constants.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/backup-sync/backup-sync-constants.js';

describe('js/backup-sync/backup-sync-constants.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["BACKUP_SYNC","DESTINATION_IDS","RESTORE_CONFIG","RESTORE_MODE","RESTORE_OPERATION","RESTORE_STATUS","RESTORE_TYPE","SYNC_STATUS","SYNC_TYPE"]);
  });

});
