/**
 * @fileoverview Unit tests for js/backup-sync/backup-destination-registry.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/backup-sync/backup-destination-registry.js';

describe('js/backup-sync/backup-destination-registry.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["getDestination","listDestinations","registerDestination"]);
  });

});
