/**
 * @fileoverview Unit tests for js/form/form-handler-validation-ui.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import '../../setup/browser-globals.js';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/form/form-handler-validation-ui.js';

describe('js/form/form-handler-validation-ui.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["clearValidationErrors","displayValidationErrors"]);
  });

});
