/**
 * @fileoverview Unit tests for js/validation/jilla-membership-validation.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import '../../setup/browser-globals.js';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/validation/jilla-membership-validation.js';

describe('js/validation/jilla-membership-validation.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["parseMembershipInt"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('parseMembershipInt accepts zero and positive integers', async () => {
      const { parseMembershipInt } = await import(MODULE);
      assert.deepEqual(parseMembershipInt(''), { valid: true, value: 0 });
      assert.deepEqual(parseMembershipInt('42'), { valid: true, value: 42 });
    });
  });

  describe('negative cases', () => {
    it('parseMembershipInt rejects decimals and letters', async () => {
      const { parseMembershipInt } = await import(MODULE);
      assert.equal(parseMembershipInt('3.5').valid, false);
      assert.equal(parseMembershipInt('abc').valid, false);
      assert.equal(parseMembershipInt('-1').valid, false);
    });
  });

  describe('edge cases', () => {
    it('parseMembershipInt rejects overly long numbers', async () => {
      const { parseMembershipInt } = await import(MODULE);
      const tooLong = '1'.repeat(13);
      assert.equal(parseMembershipInt(tooLong).valid, false);
    });
  });
  });
});
