/**
 * @fileoverview Unit tests for js/validation/validation-service.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import '../../setup/browser-globals.js';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/validation/validation-service.js';

describe('js/validation/validation-service.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["validateAddress","validateDOB","validateEmail","validateForm","validateMemberEntry","validatePIN","validatePersonalDetails","validatePhone","validateRequired"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('validateRequired accepts non-empty trimmed strings', async () => {
      const { validateRequired } = await import(MODULE);
      assert.equal(validateRequired('  value  ').valid, true);
    });

    it('validatePhone accepts ten-digit numbers and optional zero placeholder', async () => {
      const { validatePhone } = await import(MODULE);
      assert.equal(validatePhone('9876543210').valid, true);
      assert.equal(validatePhone('0').valid, true);
    });

    it('validatePIN accepts six-digit PINs', async () => {
      const { validatePIN } = await import(MODULE);
      assert.equal(validatePIN('682001').valid, true);
    });
  });

  describe('negative cases', () => {
    it('validateRequired rejects empty values', async () => {
      const { validateRequired } = await import(MODULE);
      assert.equal(validateRequired('').valid, false);
      assert.equal(validateRequired('   ').valid, false);
    });

    it('validateEmail rejects malformed addresses', async () => {
      const { validateEmail } = await import(MODULE);
      assert.equal(validateEmail('bad@').valid, false);
      assert.equal(validateEmail('a@b').valid, false);
    });

    it('validatePhone rejects invalid lengths when provided', async () => {
      const { validatePhone } = await import(MODULE);
      assert.equal(validatePhone('12345').valid, false);
      assert.equal(validatePhone('', true).valid, false);
    });

    it('validateDOB rejects future dates', async () => {
      const { validateDOB } = await import(MODULE);
      const future = new Date();
      future.setFullYear(future.getFullYear() + 1);
      assert.equal(validateDOB(future.toISOString().slice(0, 10)).valid, false);
    });
  });

  describe('edge cases', () => {
    it('validateEmail allows empty optional email', async () => {
      const { validateEmail } = await import(MODULE);
      assert.equal(validateEmail('').valid, true);
    });

    it('validatePhone allows empty optional phone', async () => {
      const { validatePhone } = await import(MODULE);
      assert.equal(validatePhone('', false).valid, true);
    });
  });
  });
});
