/**
 * @fileoverview Unit tests for js/utils/birthday-date-utils.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/utils/birthday-date-utils.js';

describe('js/utils/birthday-date-utils.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["ageTurningOnBirthday","aggregateSummaryCounts","categorizeBirthdayPersons","daysUntilNextBirthday","enrichMemberDocumentBirthParts","formatDaysRemainingLabel","formatUpcomingBirthdayCalendarLine","groupCategorizedBySabha","nextBirthdayDateFromDaysUntil","parseBirthPartsFromDob","personRowKey","resolveBirthParts"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('parseBirthPartsFromDob parses valid YYYY-MM-DD', async () => {
      const { parseBirthPartsFromDob } = await import(MODULE);
      assert.deepEqual(parseBirthPartsFromDob('1990-06-15'), { birthMonth: 6, birthDay: 15 });
    });

    it('resolveBirthParts prefers stored birthMonth and birthDay', async () => {
      const { resolveBirthParts } = await import(MODULE);
      assert.deepEqual(resolveBirthParts({ birthMonth: 3, birthDay: 10, dob: '1990-01-01' }), { birthMonth: 3, birthDay: 10 });
    });

    it('daysUntilNextBirthday returns 0 for today', async () => {
      const { daysUntilNextBirthday } = await import(MODULE);
      const ref = new Date(2026, 5, 15);
      assert.equal(daysUntilNextBirthday(6, 15, ref), 0);
    });

    it('enrichMemberDocumentBirthParts adds birth parts from dob', async () => {
      const { enrichMemberDocumentBirthParts } = await import(MODULE);
      const out = enrichMemberDocumentBirthParts({
        personalDetails: { dob: '1985-12-25' },
        members: [{ dob: '2010-01-05' }],
      });
      assert.equal(out.personalDetails.birthMonth, 12);
      assert.equal(out.members[0].birthDay, 5);
    });
  });

  describe('negative cases', () => {
    it('parseBirthPartsFromDob rejects invalid strings', async () => {
      const { parseBirthPartsFromDob } = await import(MODULE);
      assert.equal(parseBirthPartsFromDob('invalid'), null);
      assert.equal(parseBirthPartsFromDob('1990-13-01'), null);
      assert.equal(parseBirthPartsFromDob(''), null);
    });

    it('resolveBirthParts returns null for missing person', async () => {
      const { resolveBirthParts } = await import(MODULE);
      assert.equal(resolveBirthParts(null), null);
      assert.equal(resolveBirthParts({}), null);
    });
  });

  describe('edge cases', () => {
    it('formatDaysRemainingLabel handles boundary labels', async () => {
      const { formatDaysRemainingLabel } = await import(MODULE);
      assert.equal(formatDaysRemainingLabel(0), '');
      assert.equal(formatDaysRemainingLabel(1), 'Tomorrow');
      assert.equal(formatDaysRemainingLabel(5), 'In 5 days');
    });

    it('personRowKey distinguishes owner from indexed members', async () => {
      const { personRowKey } = await import(MODULE);
      assert.equal(personRowKey({ recordId: 'r1', role: 'owner', memberIndex: null }), 'r1:owner:owner');
      assert.equal(personRowKey({ recordId: 'r1', role: 'member', memberIndex: 2 }), 'r1:member:2');
    });

    it('aggregateSummaryCounts sums empty groups to zero', async () => {
      const { aggregateSummaryCounts } = await import(MODULE);
      assert.deepEqual(aggregateSummaryCounts([]), { today: 0, week: 0, month: 0 });
    });

    it('categorizeBirthdayPersons excludes past birthdays in the current month', async () => {
      const { categorizeBirthdayPersons } = await import(MODULE);
      const ref = new Date(2026, 5, 26);
      const makeRow = (dob, id) => ({
        person: { dob },
        recordId: id,
        role: 'owner',
        memberIndex: null,
      });
      const pastDobs = ['1990-06-01', '1990-06-02', '1990-06-15', '1990-06-25'];
      const result = categorizeBirthdayPersons(
        pastDobs.map((dob, i) => makeRow(dob, `past-${i}`)),
        ref,
      );
      assert.equal(result.today.length, 0);
      assert.equal(result.week.length, 0);
      assert.equal(result.month.length, 0);
    });

    it('categorizeBirthdayPersons places today and upcoming week birthdays correctly on 26 Jun', async () => {
      const { categorizeBirthdayPersons } = await import(MODULE);
      const ref = new Date(2026, 5, 26);
      const makeRow = (dob, id) => ({
        person: { dob },
        recordId: id,
        role: 'owner',
        memberIndex: null,
      });
      const result = categorizeBirthdayPersons(
        [
          makeRow('1990-06-26', 'today'),
          makeRow('1990-06-27', 'tomorrow'),
          makeRow('1990-06-30', 'end-month'),
        ],
        ref,
      );
      assert.equal(result.today.length, 1);
      assert.equal(result.today[0].row.recordId, 'today');
      assert.equal(result.week.length, 2);
      assert.deepEqual(
        result.week.map((e) => e.row.recordId).sort(),
        ['end-month', 'tomorrow'],
      );
      assert.equal(result.month.length, 0);
    });

    it('categorizeBirthdayPersons places later same-month birthdays in month after week window', async () => {
      const { categorizeBirthdayPersons } = await import(MODULE);
      const ref = new Date(2026, 5, 1);
      const makeRow = (dob, id) => ({
        person: { dob },
        recordId: id,
        role: 'owner',
        memberIndex: null,
      });
      const result = categorizeBirthdayPersons([makeRow('1990-06-20', 'later-june')], ref);
      assert.equal(result.today.length, 0);
      assert.equal(result.week.length, 0);
      assert.equal(result.month.length, 1);
      assert.equal(result.month[0].row.recordId, 'later-june');
      assert.equal(result.month[0].days, 19);
    });
  });
  });
});
