/**
 * @fileoverview Unit tests for js/utils/member-avatar-initials.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/utils/member-avatar-initials.js';

describe('js/utils/member-avatar-initials.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["MEMBER_AVATAR_SWATCH_COUNT","getMemberAvatarInitials","getMemberAvatarSwatchIndex"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('getMemberAvatarInitials follows multi-word and single-word rules', async () => {
      const { getMemberAvatarInitials } = await import(MODULE);
      assert.equal(getMemberAvatarInitials('John'), 'JO');
      assert.equal(getMemberAvatarInitials('Abhirami B M'), 'AB');
    });

    it('getMemberAvatarSwatchIndex is stable for the same seed', async () => {
      const { getMemberAvatarSwatchIndex } = await import(MODULE);
      assert.equal(getMemberAvatarSwatchIndex('Same Name'), getMemberAvatarSwatchIndex('Same Name'));
    });
  });

  describe('negative cases', () => {
    it('getMemberAvatarInitials returns placeholder for empty names', async () => {
      const { getMemberAvatarInitials } = await import(MODULE);
      assert.equal(getMemberAvatarInitials(''), '?');
      assert.equal(getMemberAvatarInitials('   '), '?');
      assert.equal(getMemberAvatarInitials(null), '?');
    });
  });

  describe('edge cases', () => {
    it('getMemberAvatarInitials handles two-character names', async () => {
      const { getMemberAvatarInitials } = await import(MODULE);
      assert.equal(getMemberAvatarInitials('Jo'), 'JO');
      assert.equal(getMemberAvatarInitials('J'), 'J');
    });

    it('getMemberAvatarSwatchIndex stays within swatch range', async () => {
      const { getMemberAvatarSwatchIndex, MEMBER_AVATAR_SWATCH_COUNT } = await import(MODULE);
      const idx = getMemberAvatarSwatchIndex('Any Seed');
      assert.ok(idx >= 0 && idx < MEMBER_AVATAR_SWATCH_COUNT);
    });
  });
  });
});
