/**
 * @fileoverview Unit tests for js/utils/target-achievement-utils.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/utils/target-achievement-utils.js';

describe('js/utils/target-achievement-utils.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["achievementRatio","aggregateActualsBySabha","countActiveMembersInRecord","countNonActivePeopleInRecord","countPeopleInRecord","defaultSabhaOrder","hasAnyJillaTargets","mergeJillaMembershipRows","resolveSabhaKey","toNonNegInt"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('achievementRatio computes percent and capped bar width', async () => {
      const { achievementRatio } = await import(MODULE);
      assert.deepEqual(achievementRatio(50, 100), { pct: 50, barPct: 50 });
      assert.deepEqual(achievementRatio(150, 100), { pct: 150, barPct: 100 });
    });

    it('countActiveMembersInRecord counts owner and members with active types', async () => {
      const { countActiveMembersInRecord } = await import(MODULE);
      const n = countActiveMembersInRecord({
        personalDetails: { membershipType: 'life_member' },
        members: [{ membershipType: 'ordinary_member' }],
        nonMembers: [{ name: 'Guest' }],
      });
      assert.equal(n, 2);
    });
  });

  describe('negative cases', () => {
    it('toNonNegInt coerces invalid values to zero', async () => {
      const { toNonNegInt } = await import(MODULE);
      assert.equal(toNonNegInt(-3), 0);
      assert.equal(toNonNegInt('x'), 0);
      assert.equal(toNonNegInt(NaN), 0);
    });

    it('achievementRatio returns null when target is zero', async () => {
      const { achievementRatio } = await import(MODULE);
      assert.equal(achievementRatio(10, 0), null);
    });

    it('resolveSabhaKey returns null for unknown sabha', async () => {
      const { resolveSabhaKey, defaultSabhaOrder } = await import(MODULE);
      assert.equal(resolveSabhaKey({ personalDetails: { pradeshikaSabha: 'Not A Sabha' } }, defaultSabhaOrder()), null);
    });
  });

  describe('edge cases', () => {
    it('mergeJillaMembershipRows preserves sabha order with missing saved rows', async () => {
      const { mergeJillaMembershipRows } = await import(MODULE);
      const rows = mergeJillaMembershipRows(null, ['A', 'B']);
      assert.equal(rows.length, 2);
      assert.equal(rows[0].psName, 'A');
      assert.equal(rows[1].lifeMembers, 0);
    });

    it('hasAnyJillaTargets is false when all targets are zero', async () => {
      const { hasAnyJillaTargets } = await import(MODULE);
      assert.equal(hasAnyJillaTargets([{ psName: 'A', lifeMembers: 0, ordinaryMembers: 0, home: 0 }]), false);
    });
  });
  });
});
