/**
 * @fileoverview Unit tests for js/locales/en.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/locales/en.js';

describe('js/locales/en.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["default"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('default export is a non-empty string map with page title', async () => {
      const mod = await import(MODULE);
      assert.ok(Object.keys(mod.default).length > 10);
      assert.equal(typeof mod.default['page.title'], 'string');
    });
  });

  describe('negative cases', () => {
    it('does not expose undefined values for core keys', async () => {
      const mod = await import(MODULE);
      assert.notEqual(mod.default['page.title'], undefined);
      assert.notEqual(mod.default['landing.title'], undefined);
    });
  });
  });
});
