/**
 * @fileoverview Unit tests for js/ui/pagination-nav-ui.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import '../../setup/browser-globals.js';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/ui/pagination-nav-ui.js';

describe('js/ui/pagination-nav-ui.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["PAGINATION_LIST_MEMBER_HUB_DESKTOP_OPTS","PAGINATION_LIST_MEMBER_HUB_OPTS","bindPageSizeSelectChange","bindPaginationNav","buildPaginationPageItems","getMemberHubPaginationOptsForViewport","populatePageSizeSelectFromDefaults"]);
  });

});
