/**
 * @fileoverview Unit tests for js/admin-stats/admin-stats-calculators.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/admin-stats/admin-stats-calculators.js';

describe('js/admin-stats/admin-stats-calculators.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["ageBucket","ageFromDob","buildAgeDistribution","buildBloodGroupDistribution","buildEducationDistribution","buildGrowthTrendMembers","buildGrowthTrendRecords","buildGrowthWeekAxis","buildMembershipDistribution","buildOccupationDistribution","buildRationDistribution","buildRecentPeopleCounts","buildRecentRecordCounts","buildSabhaDistribution","buildSabhaHouseholdInsuranceStack","buildSabhaMemberPeopleDistribution","buildSabhaNonMemberPeopleTotals","collectGenders","filterRecordsByOwnerPradeshikaSabhaKey","filterRecordsForJillaWideCharts","formatWeekRangeLabel","normalizeGender","resolveFirstOwnerPradeshikaSabhaKeyInRecords","resolveOccupationKey","resolvePradeshikaSabhaKey","toTimestampDate"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('resolveOccupationKey matches known and legacy keys', async () => {
      const { resolveOccupationKey } = await import(MODULE);
      const known = ['engineer'];
      assert.equal(resolveOccupationKey('engineer', known), 'engineer');
      assert.equal(resolveOccupationKey('Engineer', known), 'engineer');
    });

    it('ageFromDob and ageBucket compute expected values', async () => {
      const { ageFromDob, ageBucket } = await import(MODULE);
      const age = ageFromDob('2000-01-01');
      assert.ok(typeof age === 'number' && age > 0);
      assert.equal(ageBucket(10), '0–18');
      assert.equal(ageBucket(70), '60+');
    });
  });

  describe('negative cases', () => {
    it('resolveOccupationKey maps empty and unknown to sentinels', async () => {
      const { resolveOccupationKey } = await import(MODULE);
      assert.equal(resolveOccupationKey('', []), '__empty__');
      assert.equal(resolveOccupationKey(null, []), '__empty__');
      assert.equal(resolveOccupationKey('mystery job', ['engineer']), '__unknown__');
    });

    it('ageFromDob rejects invalid dates', async () => {
      const { ageFromDob } = await import(MODULE);
      assert.equal(ageFromDob(''), null);
      assert.equal(ageFromDob('not-a-date'), null);
    });
  });

  describe('edge cases', () => {
    it('normalizeGender handles short aliases', async () => {
      const { normalizeGender } = await import(MODULE);
      assert.equal(normalizeGender('m'), 'Male');
      assert.equal(normalizeGender('F'), 'Female');
      assert.equal(normalizeGender(''), 'Unknown');
    });
  });
  });
});
