/**
 * @fileoverview Unit tests for js/admin-stats/admin-stats-constants.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/admin-stats/admin-stats-constants.js';

describe('js/admin-stats/admin-stats-constants.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["BLOOD_BAR_COLORS","EDUCATION_LABELS","GROWTH_TREND_START","GROWTH_TREND_START_LABEL","LEGACY_OCCUPATION_KEYS","MEMBERSHIP_LABELS","MS_DAY","MS_WEEK","OCCUPATION_BAR_COLORS","OCCUPATION_CHART_BAR_COUNT","OCCUPATION_CHART_HEIGHT_PX","OCCUPATION_LABELS","RATION_KEY_COLORS","RATION_LABELS","STATS_CARD_TITLE_NON_MEMBERS_PS_SABHA_ADMIN","STATS_CARD_TITLE_NON_MEMBERS_PS_SUPER_ADMIN","STATS_CHART_HEALTH_INSURANCE_NO_BG","STATS_CHART_HEALTH_INSURANCE_YES_BG","STATS_CHART_MEMBERS_DATASET_LABEL","STATS_CHART_NON_MEMBERS_BAR_BG","STATS_CHART_TERM_INSURANCE_NO_BG","STATS_CHART_TERM_INSURANCE_YES_BG","STATS_HBAR_PADDING_PX","STATS_HBAR_ROW_PX","STATS_JILLA_WIDE_ALL_PS_LABEL","STATS_JILLA_WIDE_ALL_PS_VALUE","STATS_JILLA_WIDE_PS_ADMIN_SELECT_TITLE","STATS_JILLA_WIDE_PS_DROPDOWN_LABEL_OVERRIDES","STATS_NON_MEMBERS_PS_DATASET_LABEL","STATS_OCCUPATION_KEYS","STATS_PAGE_SECTION_HEADINGS","STATS_PRADESHIKA_SABHA_OTHER_LABEL","STATS_RECENT_REGISTRATION_TILES","barAxisStyle"]);
  });

});
