/**
 * @fileoverview Unit tests for js/admin-stats/admin-stats-filter.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/admin-stats/admin-stats-filter.js';

describe('js/admin-stats/admin-stats-filter.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["filterRecordsForAdminStats"]);
  });

});
