/**
 * @fileoverview Unit tests for js/services/family-tree-inference/graph-mutations.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../../setup/module-test-utils.js';

const MODULE = '../../../../js/services/family-tree-inference/graph-mutations.js';

describe('js/services/family-tree-inference/graph-mutations.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["addChild","assignParentsToChild","linkOwnerParentsIfBothPresent","linkSpouse"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('linkSpouse links nodes mutually', async () => {
      const { linkSpouse } = await import(MODULE);
      const nodes = new Map([
        ['a', { spouseId: null, childrenIds: [] }],
        ['b', { spouseId: null, childrenIds: [] }],
      ]);
      linkSpouse('a', 'b', nodes);
      assert.equal(nodes.get('a').spouseId, 'b');
      assert.equal(nodes.get('b').spouseId, 'a');
    });
  });

  describe('negative cases', () => {
    it('linkSpouse no-ops for missing nodes', async () => {
      const { linkSpouse } = await import(MODULE);
      const nodes = new Map([['a', { spouseId: null, childrenIds: [] }]]);
      linkSpouse('a', 'missing', nodes);
      assert.equal(nodes.get('a').spouseId, null);
    });
  });

  describe('edge cases', () => {
    it('addChild avoids duplicate child ids', async () => {
      const { addChild } = await import(MODULE);
      const nodes = new Map([['p', { childrenIds: ['c1'] }], ['c1', {}]]);
      addChild('p', 'c1', nodes);
      assert.deepEqual(nodes.get('p').childrenIds, ['c1']);
    });
  });
  });
});
