/**
 * @fileoverview Unit tests for js/services/family-tree-inference/index.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../../setup/module-test-utils.js';

const MODULE = '../../../../js/services/family-tree-inference/index.js';

describe('js/services/family-tree-inference/index.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["INFERENCE_RULES","cacheFamilyGraph","clearInferenceCache","getCachedFamilyGraph","runInferenceEngine"]);
  });

});
