/**
 * @fileoverview Unit tests for js/pages/landing-page.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import '../../setup/browser-globals.js';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/pages/landing-page.js';

describe('js/pages/landing-page.js', () => {
  it('loads without throwing', async () => {
    await import(MODULE);
  });

});
