/**
 * @fileoverview Unit tests for js/backup-sync/components/restore-preview.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import '../../../setup/browser-globals.js';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../../setup/module-test-utils.js';

const MODULE = '../../../../js/backup-sync/components/restore-preview.js';

describe('js/backup-sync/components/restore-preview.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["hideRestorePreview","renderRestorePreview"]);
  });

});
