/**
 * @fileoverview Unit tests for js/services/auth-service.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

const SOURCE = join(dirname(fileURLToPath(import.meta.url)), '../../../js/services/auth-service.js');
const EXPECTED_EXPORTS = ["ROLE_DISABLED","ROLE_GUEST","ROLE_PROFILE_ERROR","adminCreateUser","clearRoleCache","fetchUserRole","getCurrentUser","getUserPradeshikaSabha","getUserRole","isAdmin","isSuperAdmin","loginUser","logoutUser","onAuthChange"];

describe('js/services/auth-service.js', () => {
  it('defines expected exports in source', () => {
    const source = readFileSync(SOURCE, 'utf8');
    assert.ok(source.length > 0);
    if (EXPECTED_EXPORTS.length === 0) {
      assert.doesNotMatch(source, /^export /m);
      return;
    }
    assert.match(source, /export /);
    for (const name of EXPECTED_EXPORTS) {
      if (name === 'default') {
        assert.match(source, /export\s+default/);
      } else {
        assert.match(source, new RegExp(`\\b${name}\\b`));
      }
    }
  });

});
