/**
 * @fileoverview Unit tests for js/services/cloudinary-service.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/services/cloudinary-service.js';

describe('js/services/cloudinary-service.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["uploadToCloudinary"]);
  });

});
