/**
 * @fileoverview Unit tests for js/services/family-tree-graph-builder.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/services/family-tree-graph-builder.js';

describe('js/services/family-tree-graph-builder.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["OWNER_NODE_ID","buildFamilyGraphFromRecord","countHouseholdMembership","isSingleMemberHousehold","normalizeRelationshipKey"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('normalizeRelationshipKey lowercases relationship values', async () => {
      const { normalizeRelationshipKey } = await import(MODULE);
      assert.equal(normalizeRelationshipKey('SON'), 'son');
      assert.equal(normalizeRelationshipKey('Daughter_In_Law'), 'daughter_in_law');
    });
  });

  describe('negative cases', () => {
    it('normalizeRelationshipKey returns empty string for nullish input', async () => {
      const { normalizeRelationshipKey } = await import(MODULE);
      assert.equal(normalizeRelationshipKey(null), '');
      assert.equal(normalizeRelationshipKey(undefined), '');
    });
  });

  describe('edge cases', () => {
    it('normalizeRelationshipKey trims whitespace', async () => {
      const { normalizeRelationshipKey } = await import(MODULE);
      assert.equal(normalizeRelationshipKey('  spouse  '), 'spouse');
    });
  });
  });
});
