/**
 * @fileoverview Unit tests for js/services/member-person-search.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/services/member-person-search.js';

describe('js/services/member-person-search.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["PERSON_SEARCH_FACETS","ageYearsFromDobForFilter","applyPersonFilters","applyTextFilter","createEmptyFilterState","expandToPersonRows","facetValueLabel","formatHouseholdAddress","normalizePhoneDigits","personAgeFacetBucketId","personRoleBadgeLabel","whatsappHref"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('formatHouseholdAddress joins populated address lines', async () => {
      const { formatHouseholdAddress } = await import(MODULE);
      const addr = formatHouseholdAddress({
        address: { address1: 'Line 1', address2: 'Line 2', place: 'Kochi', pin: '682001' },
      });
      assert.equal(addr, 'Line 1, Line 2, Kochi, 682001');
    });
  });

  describe('negative cases', () => {
    it('formatHouseholdAddress returns empty string when address missing', async () => {
      const { formatHouseholdAddress } = await import(MODULE);
      assert.equal(formatHouseholdAddress({}), '');
      assert.equal(formatHouseholdAddress(null), '');
    });
  });
  });
});
