/**
 * @fileoverview Unit tests for js/services/pagination-service.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/services/pagination-service.js';

describe('js/services/pagination-service.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["getPaginationState","getTotalPages","paginate","resetPage","setPaginationState"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('paginate returns correct slices', async () => {
      const { paginate } = await import(MODULE);
      const records = [1, 2, 3, 4, 5];
      assert.deepEqual(paginate(records, 1, 2), [1, 2]);
      assert.deepEqual(paginate(records, 3, 2), [5]);
    });

    it('getTotalPages computes page count', async () => {
      const { getTotalPages } = await import(MODULE);
      assert.equal(getTotalPages(25, 10), 3);
    });
  });

  describe('negative cases', () => {
    it('paginate does not mutate the source array', async () => {
      const { paginate } = await import(MODULE);
      const records = [1, 2, 3];
      const copy = [...records];
      paginate(records, 1, 2);
      assert.deepEqual(records, copy);
    });
  });

  describe('edge cases', () => {
    it('getTotalPages returns at least one page for zero records', async () => {
      const { getTotalPages } = await import(MODULE);
      assert.equal(getTotalPages(0, 10), 1);
    });

    it('resetPage and setPaginationState update state', async () => {
      const { setPaginationState, resetPage, getPaginationState, paginate } = await import(MODULE);
      setPaginationState({ currentPage: 3, pageSize: 5 });
      assert.equal(getPaginationState().currentPage, 3);
      resetPage();
      assert.equal(getPaginationState().currentPage, 1);
      assert.deepEqual(paginate([1, 2, 3, 4, 5, 6], undefined, 5), [1, 2, 3, 4, 5]);
    });
  });
  });
});
