/**
 * @fileoverview Unit tests for js/services/search-service.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/services/search-service.js';

describe('js/services/search-service.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["filterMembersByHealthInsuranceSet","filterMembersByHouseholdComposition","filterMembersByRationCardSet","filterMembersBySabha","filterMembersBySabhaSet","filterMembersByWelfare","searchMembers"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('searchMembers matches house name case-insensitively', async () => {
      const { searchMembers } = await import(MODULE);
      const records = [{ personalDetails: { houseName: 'Green Villa', name: 'Owner', phone: '9876543210', address: { pin: '682001' } } }];
      const hits = searchMembers(records, 'green');
      assert.equal(hits.length, 1);
    });

    it('filterMembersBySabha matches exact sabha', async () => {
      const { filterMembersBySabha } = await import(MODULE);
      const records = [
        { personalDetails: { pradeshikaSabha: 'Aluva' } },
        { personalDetails: { pradeshikaSabha: 'Tripunithura' } },
      ];
      assert.equal(filterMembersBySabha(records, 'aluva').length, 1);
    });
  });

  describe('negative cases', () => {
    it('searchMembers returns all records for blank query', async () => {
      const { searchMembers } = await import(MODULE);
      const records = [{ id: 1 }, { id: 2 }];
      assert.equal(searchMembers(records, '   ').length, 2);
    });

    it('filterMembersBySabha returns all records when sabha is empty', async () => {
      const { filterMembersBySabha } = await import(MODULE);
      const records = [{ personalDetails: { pradeshikaSabha: 'Aluva' } }];
      assert.equal(filterMembersBySabha(records, '').length, 1);
    });
  });

  describe('edge cases', () => {
    it('filterMembersBySabhaSet returns all when selection is empty', async () => {
      const { filterMembersBySabhaSet } = await import(MODULE);
      const records = [{ personalDetails: { pradeshikaSabha: 'Aluva' } }];
      assert.equal(filterMembersBySabhaSet(records, new Set()).length, 1);
    });

    it('filterMembersByHouseholdComposition matches non-member households', async () => {
      const { filterMembersByHouseholdComposition } = await import(MODULE);
      const records = [{ personalDetails: {}, members: [], nonMembers: [{ name: 'Guest' }] }];
      const hits = filterMembersByHouseholdComposition(records, new Set(['non_member']));
      assert.equal(hits.length, 1);
    });
  });
  });
});
