/**
 * @fileoverview Unit tests for js/services/sort-service.js
 * @generated by tests/setup/generate-module-tests.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  assertHasExports,
  assertModuleLoads,
} from '../../setup/module-test-utils.js';

const MODULE = '../../../js/services/sort-service.js';

describe('js/services/sort-service.js', () => {
  it('loads and exposes exports', async () => {
    const mod = await import(MODULE);
    assertHasExports(mod, ["sortMembers"]);
  });

  describe('behavioral cases', () => {
  describe('positive cases', () => {
    it('sortMembers sorts by name ascending and descending', async () => {
      const { sortMembers } = await import(MODULE);
      const records = [
        { personalDetails: { name: 'Zara' } },
        { personalDetails: { name: 'Amy' } },
      ];
      const asc = sortMembers(records, 'name', 'asc');
      assert.equal(asc[0].personalDetails.name, 'Amy');
      const desc = sortMembers(records, 'name', 'desc');
      assert.equal(desc[0].personalDetails.name, 'Zara');
    });
  });

  describe('negative cases', () => {
    it('sortMembers does not mutate the input array', async () => {
      const { sortMembers } = await import(MODULE);
      const records = [{ personalDetails: { name: 'B' } }, { personalDetails: { name: 'A' } }];
      const before = records.map((r) => r.personalDetails.name);
      sortMembers(records, 'name', 'asc');
      assert.deepEqual(records.map((r) => r.personalDetails.name), before);
    });
  });

  describe('edge cases', () => {
    it('sortMembers treats missing names as empty strings', async () => {
      const { sortMembers } = await import(MODULE);
      const records = [{ personalDetails: {} }, { personalDetails: { name: 'Amy' } }];
      const sorted = sortMembers(records, 'name', 'asc');
      assert.equal(sorted[0].personalDetails.name, undefined);
      assert.equal(sorted[1].personalDetails.name, 'Amy');
    });
  });
  });
});
